from enum import Enum


class StableStringEnum(str, Enum):
    """String enum whose member values are the public and persisted contract."""


class ScopeType(StableStringEnum):
    COMPANY = "COMPANY"
    DEPARTMENT = "DEPARTMENT"
    PROJECT = "PROJECT"
    PERSONAL_DRAFT = "PERSONAL_DRAFT"


class AccessLevel(StableStringEnum):
    INTERNAL = "INTERNAL"
    RESTRICTED = "RESTRICTED"
    CONFIDENTIAL = "CONFIDENTIAL"


class ResourceAction(StableStringEnum):
    READ = "READ"
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    REVIEW = "REVIEW"
    APPROVE = "APPROVE"
    MANAGE = "MANAGE"


class SourceType(StableStringEnum):
    DOCUMENT = "DOCUMENT"
    EXPERT_NOTE = "EXPERT_NOTE"
    MANUAL_ATTESTATION = "MANUAL_ATTESTATION"


class SourceStatus(StableStringEnum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class ProcessingStatus(StableStringEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    READY = "READY"
    FAILED = "FAILED"


class PublicationStatus(StableStringEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    SUPERSEDED = "SUPERSEDED"
    WITHDRAWN = "WITHDRAWN"
    ARCHIVED = "ARCHIVED"


class IngestionJobType(StableStringEnum):
    DOCUMENT_INGESTION = "DOCUMENT_INGESTION"
    DOCUMENT_EMBEDDING = "DOCUMENT_EMBEDDING"


class IngestionJobStatus(StableStringEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    DEAD_LETTER = "DEAD_LETTER"
    CANCELLED = "CANCELLED"


class DocumentBlockType(StableStringEnum):
    PARAGRAPH = "PARAGRAPH"
    HEADING = "HEADING"
    TABLE = "TABLE"
    SPREADSHEET_ROWS = "SPREADSHEET_ROWS"


class IngestionErrorCode(StableStringEnum):
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    STORAGE_READ_FAILED = "STORAGE_READ_FAILED"
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    FILE_SIGNATURE_MISMATCH = "FILE_SIGNATURE_MISMATCH"
    EMPTY_DOCUMENT = "EMPTY_DOCUMENT"
    INVALID_TEXT_ENCODING = "INVALID_TEXT_ENCODING"
    ENCRYPTED_PDF = "ENCRYPTED_PDF"
    OCR_REQUIRED = "OCR_REQUIRED"
    PDF_PAGE_LIMIT_EXCEEDED = "PDF_PAGE_LIMIT_EXCEEDED"
    OFFICE_ZIP_INVALID = "OFFICE_ZIP_INVALID"
    ZIP_BOMB_SUSPECTED = "ZIP_BOMB_SUSPECTED"
    MACRO_CONTENT_REJECTED = "MACRO_CONTENT_REJECTED"
    XLSX_LIMIT_EXCEEDED = "XLSX_LIMIT_EXCEEDED"
    EXTRACTED_TEXT_LIMIT_EXCEEDED = "EXTRACTED_TEXT_LIMIT_EXCEEDED"
    PARSER_FAILED = "PARSER_FAILED"
    CHUNKING_FAILED = "CHUNKING_FAILED"
    DATABASE_WRITE_FAILED = "DATABASE_WRITE_FAILED"
    LEASE_LOST = "LEASE_LOST"
    UNKNOWN_INGESTION_ERROR = "UNKNOWN_INGESTION_ERROR"
    EMBEDDING_PROVIDER_UNAVAILABLE = "EMBEDDING_PROVIDER_UNAVAILABLE"
    EMBEDDING_REVISION_MISMATCH = "EMBEDDING_REVISION_MISMATCH"
    EMBEDDING_INPUT_TOO_LONG = "EMBEDDING_INPUT_TOO_LONG"
    EMBEDDING_INVALID_OUTPUT = "EMBEDDING_INVALID_OUTPUT"
    EMBEDDING_INCOMPLETE = "EMBEDDING_INCOMPLETE"


class EmbeddingProfileStatus(StableStringEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class EmbeddingProviderType(StableStringEnum):
    LOCAL_E5 = "LOCAL_E5"


class RetrievalMode(StableStringEnum):
    HYBRID = "HYBRID"
    FTS_ONLY = "FTS_ONLY"
    VECTOR_ONLY = "VECTOR_ONLY"
